/*******NAME:       Amany Sabry*******/
/*******DATE:       9/2024***********/
/*******Version:    1.o*************/


#ifndef MDIO_CONFIG_H
#define MDIO_CONFIG_H

//for pin direction//DDR REG
/*set macro for direction
  PRIVATE_OUTPUT    1
  PRIVATE_INPUT     0  */

//for port A
#define MDIO_PA0_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PA1_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PA2_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PA3_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PA4_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PA5_DIRECTION   PRIVATE_INPUT
#define MDIO_PA6_DIRECTION   PRIVATE_INPUT
#define MDIO_PA7_DIRECTION   PRIVATE_INPUT
//for port B
#define MDIO_PB0_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB1_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB2_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB3_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB4_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB5_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB6_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PB7_DIRECTION   PRIVATE_OUTPUT
//for port C
#define MDIO_PC0_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PC1_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PC2_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PC3_DIRECTION   PRIVATE_INPUT
#define MDIO_PC4_DIRECTION   PRIVATE_INPUT
#define MDIO_PC5_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PC6_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PC7_DIRECTION   PRIVATE_OUTPUT
//for port D
#define MDIO_PD0_DIRECTION   PRIVATE_INPUT
#define MDIO_PD1_DIRECTION   PRIVATE_OUTPUT
#define MDIO_PD2_DIRECTION   PRIVATE_INPUT
#define MDIO_PD3_DIRECTION   PRIVATE_INPUT
#define MDIO_PD4_DIRECTION   PRIVATE_INPUT
#define MDIO_PD5_DIRECTION   PRIVATE_INPUT
#define MDIO_PD6_DIRECTION   PRIVATE_INPUT
#define MDIO_PD7_DIRECTION   PRIVATE_OUTPUT

//set value for output and input
/*
 // set macro for values
 PRIVATE_OUTPUT_HIGH  1
 PRIVATE_OUTPUT_LOW  0
 PRIVATE_INPUT_FLOATING  0
 PRIVATE_INPUT_PULLEDUP  1*/

// for port A
#define MDIO_PA0_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PA1_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PA2_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PA3_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PA4_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PA5_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PA6_VALUE   PRIVATE_INPUT_PULLEDUP
#define MDIO_PA7_VALUE   PRIVATE_INPUT_PULLEDUP
//for port B
#define MDIO_PB0_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PB1_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PB2_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PB3_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PB4_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PB5_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PB6_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PB7_VALUE   PRIVATE_INPUT_FLOATING
//for port C
#define MDIO_PC0_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PC1_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PC2_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PC3_VALUE   PRIVATE_INPUT_PULLEDUP
#define MDIO_PC4_VALUE   PRIVATE_INPUT_PULLEDUP
#define MDIO_PC5_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PC6_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PC7_VALUE   PRIVATE_OUTPUT_LOW
//for port D
#define MDIO_PD0_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PD1_VALUE   PRIVATE_OUTPUT_LOW
#define MDIO_PD2_VALUE   PRIVATE_INPUT_PULLEDUP
#define MDIO_PD3_VALUE   PRIVATE_INPUT_PULLEDUP
#define MDIO_PD4_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PD5_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PD6_VALUE   PRIVATE_INPUT_FLOATING
#define MDIO_PD7_VALUE   PRIVATE_OUTPUT_LOW




#endif
