#include "STD_TYPE.h"
#include "BIT_MAC_FUC.h"

#include "MOTORS_CONFIG.h"
#include "MOTORS_PRIVATE.h"
#include "MOTORS_INTERFACE.h"
#include "MDIO_Interface.h"
#include "MTimer0&2_Interface.h"


void Motor_Init(void){
	MDIO_Init();
	MTMR0_voidInit();
	MTMR2_voidInit();
}
void Motor_SetDirection(u8 Direction){
	switch(Direction){
	case MOTOR_FORWARD:
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinHigh);
	    MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
	    MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinHigh);
		//MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);
	    //MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		break;

	case MOTOR_FORWARD_RIGHT:
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinHigh);
		break;

	case  MOTOR_FORWARD_LEFT:
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinHigh);
		break;


	case  MOTOR_BACKWARD:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);
		//MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinHigh);
		//MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		break;

	case MOTOR_BACKWARD_RIGHT :
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);

		break;


	case MOTOR_BACKWARD_LEFT:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);
		break;

	case  MOTOR_TURN_RIGHT:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		break;

	case  MOTOR_TURN_LEFT:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);
		break;
	case MOTOR_STOP:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		break;
	case MOTOR_RightSmooth:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinLow);
		break;
	case MOTOR_LeftSmooth:
		MDIO_u8SetPinValue(MOTOR_A_IN1_PORT,MOTOR_A_IN1_PIN,MDIO_PinHigh);
		MDIO_u8SetPinValue(MOTOR_A_IN2_PORT,MOTOR_A_IN2_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN3_PORT,MOTOR_B_IN3_PIN,MDIO_PinLow);
		MDIO_u8SetPinValue(MOTOR_B_IN4_PORT,MOTOR_B_IN4_PIN,MDIO_PinHigh);
		break;
	}
}
	void Motor_SetSpeed(u8 SpeedA,u8 SpeedB ){
	MTMR0_voidSetOCR0Value(SpeedA);//MOTOR A TIMER0
	MTMR2_voidSetOCR2Value(SpeedB);//MOTOR B TIMER2
}


